interface jabra-deposits-handler {
  use jabratech:common/types.{response};
  use types.{jabra-deposits-response};

  get: func(currency: string, current-spot: f64) -> result<jabra-deposits-response, response>;
  
}