interface types {

    record exchanges-wallet{
        exchange-name: string,
        amount: f64,
        delta: f64,
        pnl: f64
    }
    record collateral-owed{
        counter-party: string,
        currency: string,
        exchange: string,
        amount: f64,
        equity-usd: f64,
    }
    record exchanges-wallet-response{
        total-amount: f64,
        pnl: f64,
        total-delta: f64,
        exchanges-wallet: list<exchanges-wallet>,
        collateral-owed: list<collateral-owed>,
        total-deribit-collateral: f64,
        total-current-wallet-balances: f64,
        total-equity-usd: f64,
    }

    record jabra-deposits-response{
        code: s16,
        message: string,
        data: exchanges-wallet-response
    }

}